### ISSUE TITLE
Coding Generated for SR24 and Navio2(Ardupilot)

### ISSUE THREAD

**Issue by jack1383** [h-elsner/SR24_decode#1]
Hello, I am a novice in programming I am building a drone with Navio2 and Raspberry pi 4B, I want to interface the Yuneec ST16 and RS24 controller on my Raspberry pi 4B but they may have a link with Arducopter (Ardupilot), is it possible to configure the link between Arducopter Navio2 and Yunnec ST16 controller (SR24),   Thank you for supporting me in my new project!

**Comment by h-elsner** [comment]
SR24 is not transparent for MAVlink messages. It means all advanced features that Ardupilot cannot be used. ST16/SR24 use its own proprietary message format described in "UART_ST24_raw.ods".
For simply use of RC channels from ST16 via SR24 there is a converter to SBUS. Maybe this is the answer for ARDUpilot.
https://yuneecpilots.com/threads/st16-v1.20747/page-7#post-248123

I do not understand how Navio2 and RaspberryPi communicate and for what. I understand it is a complete system that only will be configured. I cannot see any API or interface description.

**Comment by jack1383** [comment]
thank you for your quick response I will try your recommendations and convert sr24 to sbus with the adapter designed for this effect, thank you again and good work in your future projects

Envoyé de mon iPhone

Le 27 mars 2023 à 03:53, H. Elsner ***@***.***> a écrit :

﻿

SR24 is not transparent for MAVlink messages. It means all advanced features that Ardupilot cannot be used. ST16/SR24 use its own proprietary message format described in "UART_ST24_raw.ods".
For simply use of RC channels from ST16 via SR24 there is a converter to SBUS. Maybe this is the answer for ARDUpilot.
https://yuneecpilots.com/threads/st16-v1.20747/page-7#post-248123

I do not understand how Navio2 and RaspberryPi communicate and for what. I understand it is a complete system that only will be configured. I cannot see any API or interface description.
