### ISSUE TITLE
Typhoon H SR24 or Q500+ 2.4 GHz receiver?

### ISSUE THREAD

**Issue by AgentSmith0** [h-elsner/SR24_decode#2]
Hello, Yuneec offers the following receivers:
https://shop.yuneec.com/eu/spare-parts/q500-g-4k/q500-2.4-ghz-receiver/
https://shop.yuneec.com/eu/spare-parts/typhoon-h/typhoon-h-sr24-receiver-board/

I have an ST16 (for a Typhoon H), does it work the same with both receivers or are there any differences?

**Comment by h-elsner** [comment]
ST16 will work with both. It are basically the same. Some comes with shield some without but functionality is similar. Take the cheapest ;-)
